#sudo: required

os:
 - linux

language: cpp

compiler:
 - gcc
 - clang

before_script:
 - cmake .

script: 
 - make

addons:
 apt:
  sources:
   - george-edison55-precise-backports
  packages:
   - cmake
   - cmake-data
