#sudo: required

os:
 - linux
 - osx

language: cpp

compiler:
 - gcc
 - clang

addons:
 apt:
  sources:
   - george-edison55-precise-backports
  packages:
   - cmake
   - cmake-data

before_install:
    
before_script:
 - cmake .

script: 
 - make
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd MyiOSStaticLibrary; xcodebuild -scheme UniversalStaticLibrary ; cd .. ; fi  
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd MyiOSStaticLibrary; xcodebuild test -scheme UnitTests -destination 'platform=iOS Simulator,name=iPhone 6' ; cd .. ; fi  
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd MyiOSDemoApp; xcodebuild -scheme MyiOSDemoApp -destination 'platform=iOS Simulator,name=iPhone 6' ; cd .. ; fi  

